### ISSUE TITLE
patternProperties not working

### ISSUE THREAD

**Issue by jethrobear** [ghandic/jsf#18]
Hi,

I am having issues with JSF when `patternProperties` was defined. See below:

JSON Schema:
```
{
    "title": "XXXXX",
    "description": "XXXXX",
    "type": "object",

    "definitions": {
        "InstructionItem": {
            "type": "object",
            "properties": {
                "Command": {
                    "description": "XXXX",
                    "type": "string"
                },
                "ExecutionTimeout": {
                    "description": "XXXX",
                    "type": "integer"
                },
                "ExecutionType": {
                    "description": "XXXXX",
                    "type": "string"
                },
                "InvokeSequence": {
                    "description": "XXXXXX",
                    "type": "integer"
                },
                "MachineLabel": {
                    "description": "XXXX",
                    "type": "string"
                },
                "NodeReference": {
                    "description": "XXXXX",
                    "type": "string"
                }
            },
            "required": [
                "Command",
                "ExecutionTimeout",
                "ExecutionType",
                "InvokeSequence",
                "MachineLabel",
                "NodeReference"
            ]
        },
        "InstructionStep": {
            "type": "object",
            "properties": {
                "CertificateURL": {
                    "description": "XXXX",
                    "type": "string"
                },
                "Description": {
                    "description": "XXXX",
                    "type": "string"
                },
                "ManualStep": {
                    "description": "XXXX",
                    "type": "boolean"
                },
                "RunAsUser": {
                    "description": "XXXX",
                    "type": "string"
                },
                "StepCommand": {
                    "description": "XXXX",
                    "type": "string"
                },
                "StepFunction": {
                    "description": "XXXX",
                    "type": "string"
                },
                "UseFunction": {
                    "description": "XXXX",
                    "type": "boolean"
                },
                "StepRun": {
                    "description": "XXXX",
                    "type": "string"
                },
                "cwd": {
                    "description": "XXXX",
                    "type": "string"
                }
            },
            "required": [
                "CertificateURL",
                "Description",
                "ManualStep",
                "RunAsUser",
                "StepCommand",
                "StepFunction",
                "UseFunction",
                "StepRun",
                "cwd"
            ]
        }
    },


    "properties": {
        "AreNotificationsEnabled": {
            "description": "XXXX",
            "type": "boolean"
        },
        "Description": {
            "description": "XXXXX",
            "type": "string"
        },
        "Instructions": {
            "description": "XXXXX",
            "type": "array",
            "items": {
                "$ref": "#/definitions/InstructionItem"
            }
        },
        "IsActive": {
            "description": "XXXXX",
            "type": "boolean"
        },
        "IsCustomerFacing": {
            "description": "XXXXXX",
            "type": "boolean"
        },
        "IsAdminFacing": {
            "description": "XXXXX",
            "type": "boolean"
        },
        "IsSystem": {
            "description": "XXXXX",
            "type": "boolean"
        },
        "Name": {
            "description": "XXXXXX",
            "type": "string"
        },
        "Nodes":{
            "description": "XXXXX",
            "type": "object",
            "patternProperties": {
                "[A-Z_]+": {
                    "description": "XXXXX",
                    "type": "object",
                    "properties": {
                        "AdminTask": {
                            "description": "XXXXX",
                            "type": "object",
                            "properties": {
                                "AdminFun": {
                                    "description": "XXXXX",
                                    "type": "object",
                                    "patternProperties": {
                                        "[A-Z_]+": {
                                            "description": "XXXX",
                                            "type": "object",
                                            "properties": {
                                                "Instructions": {
                                                    "description": "XX",
                                                    "type": "object",
                                                    "patternProperties": {
                                                        "[A-Z_-]+": {
                                                            "$ref": "#/definitions/InstructionStep"
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "required": [
        "AreNotificationsEnabled",
        "Description",
        "Instructions",
        "IsActive",
        "IsCustomerFacing",
        "IsAdminFacing",
        "IsSystem",
        "Name",
        "Nodes"
    ]
}
```

Error message:
```
> jsf --schema .\af.schema --instance .\t.json
Traceback (most recent call last):
  File "%HOME%\jsonvalidator\env\lib\site-packages\jsf\schema_types\object.py", line 40, in generate
    return super().generate(context)
  File "%HOME%\jsonvalidator\env\lib\site-packages\jsf\schema_types\base.py", line 49, in generate
    raise ProviderNotSetException()
jsf.schema_types.base.ProviderNotSetException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "%HOME%\jsonvalidator\env\lib\site-packages\jsf\schema_types\object.py", line 40, in generate
    return super().generate(context)
  File "%HOME%\jsonvalidator\env\lib\site-packages\jsf\schema_types\base.py", line 49, in generate
    raise ProviderNotSetException()
jsf.schema_types.base.ProviderNotSetException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\python3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "%HOME%\jsonvalidator\env\Scripts\jsf.exe\__main__.py", line 7, in <module>
  File "%HOME%\jsonvalidator\env\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "%HOME%\jsonvalidator\env\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "%HOME%\jsonvalidator\env\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "%HOME%\jsonvalidator\env\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "%HOME%\jsonvalidator\env\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "%HOME%\jsonvalidator\env\lib\site-packages\typer\main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "%HOME%\jsonvalidator\env\lib\site-packages\jsf\cli.py", line 19, in main
    JSF.from_json(schema).to_json(instance)
  File "%HOME%\jsonvalidator\env\lib\site-packages\jsf\parser.py", line 143, in to_json
    json.dump(self.generate(), f, indent=2)
  File "%HOME%\jsonvalidator\env\lib\site-packages\jsf\parser.py", line 131, in generate
  File "%HOME%\jsonvalidator\env\lib\site-packages\jsf\schema_types\object.py", line 42, in generate
    return {o.name: o.generate(context) for o in self.properties if self.should_keep(o.name)}
  File "%HOME%\jsonvalidator\env\lib\site-packages\jsf\schema_types\object.py", line 42, in <dictcomp>
    return {o.name: o.generate(context) for o in self.properties if self.should_keep(o.name)}
  File "%HOME%\jsonvalidator\env\lib\site-packages\jsf\schema_types\object.py", line 42, in generate
    return {o.name: o.generate(context) for o in self.properties if self.should_keep(o.name)}
TypeError: 'NoneType' object is not iterable
```

I've tried replacing `patternProperties` with `properties` and it worked. 

Thanks,

**Comment by reubano** [comment]
I'm getting a similar error and am not using `patternProperties`. Was this particular issue ever resolved?

**Comment by ghandic** [comment]
Hey @reubano could you add a sample json schema?
