### ISSUE TITLE
AttributeError when definitions are in particluar order

### ISSUE THREAD

**Issue by vlade11115** [ghandic/jsf#80]
Hi.
I have a simple schema:
<details>
  <summary>schema.json</summary>
  
```json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "a_arr": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/A"
      }
    }
  },
  "definitions": {
    "A": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "bar": {
          "$ref": "#/definitions/B"
        }
      }
    },
    "B": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "foo": {
          "type": "string"
        }
      }
    }
  }
}
```
</details>

When I am trying to generate data, I hit an error.
Code sample:
```python
import json

from jsf import JSF

s = json.load(open("schema.json"))
f = JSF(s)
fake_json = f.generate()
print(fake_json)

```

I got this traceback:
<details>
  <summary>Traceback</summary>
  
```
Traceback (most recent call last):
  File "/Users/vlad/Library/Application Support/JetBrains/PyCharm2023.2/scratches/scratch_105.py", line 6, in <module>
    mismo_faker = JSF(mismo)
  File "/Users/vlad/Projects/test/venv/lib/python3.9/site-packages/jsf/parser.py", line 53, in __init__
    self._parse(schema)
  File "/Users/vlad/Projects/test/venv/lib/python3.9/site-packages/jsf/parser.py", line 179, in _parse
    item = self.__parse_definition(name, path=f"#/{def_tag}", schema=definition)
  File "/Users/vlad/Projects/test/venv/lib/python3.9/site-packages/jsf/parser.py", line 140, in __parse_definition
    return self.__parse_object(name, path, schema)
  File "/Users/vlad/Projects/test/venv/lib/python3.9/site-packages/jsf/parser.py", line 65, in __parse_object
    props.append(self.__parse_definition(_name, path=f"{path}/{_name}", schema=definition))
  File "/Users/vlad/Projects/test/venv/lib/python3.9/site-packages/jsf/parser.py", line 164, in __parse_definition
    cls.name = name
AttributeError: 'NoneType' object has no attribute 'name'

Process finished with exit code 1
```
</details>

My pip freeze:

<details>
  <summary>pip freeze</summary>

```
annotated-types==0.5.0
attrs==23.1.0
certifi==2023.7.22
charset-normalizer==3.2.0
Faker==19.3.1
idna==3.4
jsf==0.8.0
jsonschema==4.19.0
jsonschema-specifications==2023.7.1
pydantic==2.3.0
pydantic_core==2.6.3
python-dateutil==2.8.2
referencing==0.30.2
requests==2.31.0
rpds-py==0.10.0
rstr==3.2.1
six==1.16.0
smart-open==6.3.0
typing_extensions==4.7.1
urllib3==2.0.4
```
</details>

However, when I reorder the definitions, it is working as expected.

<details>
  <summary>Working schema</summary>
  
```json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "a_arr": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/A"
      }
    }
  },
  "definitions": {
    "B": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "foo": {
          "type": "string"
        }
      }
    },
    "A": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "bar": {
          "$ref": "#/definitions/B"
        }
      }
    }
  }
}
```
</details>
Note that the definition of B is before the definition of A.
In my case, I cannot reorder definitions, as I have a big schema with many definitions coming from my customers.
I would like to help fix this, but I would appreciate guidance on how to fix it.

**Comment by ghandic** [comment]
Interesting! Makes sense though as we do a top down single pass. Would need to build up some kind of dependency tree and solve it. Non trivial change, would be worth looking at how and if json schema faker (npm) have solved it.

**Comment by vlade11115** [comment]
@ghandic I can confirm that https://json-schema-faker.js.org/ works correctly with my schema.
I agree that this is nontrivial, my initial attempt to fix it failed.
